include: package:lint/strict.yaml

linter:
  rules:
    sort_constructors_first: false
    prefer_double_quotes: true
    lines_longer_than_80_chars: true

analizer:
  errors:
    prefer_if_elements_to_contidional_expressions: ignore
    todo: info
